# Generated by Django 3.0.6 on 2021-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='my blog post', max_length=225),
        ),
    ]
